import { Metadata } from "next";

import NavBar from "@/components/client/layout/nav/index";
import Hero from "@/components/client/landing/hero";
import CategorySection from "@/components/client/landing/category-section";
import ProductsSection from "@/components/client/landing/products-section";
import FeaturedProductsSection from "@/components/client/landing/features-products";
import NewArrivalsProductsSection from "@/components/client/landing/new-arrivals";
import Footer from "@/components/client/layout/footer";
import WishlistPage from "./(client)/wishlist/page";
import CartPage from "./(client)/cart/page";

export const metadata: Metadata = {
  title: "Home | Nepali Pasal",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      {/* Navbar */}
      <NavBar />

      <main>
        {/* Hero */}
        <Hero />

        {/* Categories */}
        <CategorySection />

        {/* All Products */}
        <ProductsSection />

        {/* Featured Products */}
        <FeaturedProductsSection />

        {/* New Arrival Products */}
        <NewArrivalsProductsSection />
      </main>

      {/* Footer */}
      <Footer />
    </>
  );
}
